---
title: "Main"
author: "EJ,David,keem"
date: "2026-04-08"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read.csv("data.csv")
head(data)
```
This data set is about the different models of different cars that contains car listing, where each row represents a single vehicle and each column represent a specific feature of the car. That also has numerical and categorical variables.
```{r}
data

```

```{r}
#this is the highest priced vehicle for each group of Number.of.Doors
library(ggplot2)
ggplot(data, aes(Number.of.Doors, MSRP)) + 
  geom_col()
```

```{r}
library(dplyr)

data %>%
  group_by(Number.of.Doors) %>%
  summarize(avg_MSRP = mean(MSRP, na.rm = TRUE)) %>%
  ggplot(aes(x = Number.of.Doors, y = avg_MSRP)) +
  geom_col()
#this checks the average of each type of Number.of.Doors

#What is the average price for tow door cars a s opposed to four door cars?
```


```{r}
library(shiny)
library(plotly)
library(dplyr)

ui <- fluidPage(
  titlePanel("Interactive MSRP Analysis"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput(
        "xvar",
        "Choose influencing factor:",
        choices = c("Engine Horsepower" = "Engine.HP",
                    "Highway MPG" = "highway.MPG",
                    "City MPG" = "city.mpg")
      ),
      
      selectInput(
        "make_filter",
        "Filter by Make:",
        choices = c("All", sort(unique(data$Make))),
        selected = "All"
      )
    ),
    
    mainPanel(
      plotlyOutput("msrp_plot")
    )
  )
)

server <- function(input, output) {
  
  filtered_data <- reactive({
    if (input$make_filter == "All") {
      data
    } else {
      data %>% filter(Make == input$make_filter)
    }
  })
  
  output$msrp_plot <- renderPlotly({
    df <- filtered_data()
    
    x_values <- df[[input$xvar]]
    
    plot_ly(
      data = df,
      x = ~x_values,
      y = ~MSRP,
      type = "scatter",
      mode = "markers",
      text = ~paste0(
        "Make: ", Make,
        "<br>Model: ", Model,
        "<br>", input$xvar, ": ", x_values,
        "<br>MSRP: $", MSRP
      ),
      hoverinfo = "text"
    ) %>%
      layout(
        title = paste(input$xvar, "vs MSRP"),
        xaxis = list(title = input$xvar),
        yaxis = list(title = "MSRP")
      )
  })
}

shinyApp(ui = ui, server = server)
```

